version: '3.3'

services:
  
  client:
    build:
      context: ../
      dockerfile: infra/frontend/Dockerfile
    ports:
       - "3000:3000"
    container_name: client
    networks:
      - femsa

  database:
      image: mysql
      container_name: database
      restart: always
      ports:
        - '3306:3306'
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - ~/apps/mysql:/var/lib/femsa
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: test
        MYSQL_PASSWORD: test
        MYSQL_ROOT_HOST: '%'
        TIMEZONE: UTC
      networks:
        - femsa

  server:
    build: 
      context: ../
      dockerfile: infra/backend/Dockerfile
    restart: always
    ports:
      - "6000"
    container_name: server
    networks:
      - femsa
    depends_on:
      - database

networks:
  femsa: